version: "3.8"

services:
  test_db:
    image: postgres:12
    environment:
      POSTGRES_DB: "test_mydatabase"
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "mypassword"
    ports:
      - "5432:5432"
