"""Init base tables

Revision ID: 0563d1e023f8
Revises: 
Create Date: 2025-04-15 09:44:33.378662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0563d1e023f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('SINGLE_PLAYER', 'MULTIPLAYER', name='gamemode').create(op.get_bind())
    op.create_table('player',
                    sa.Column('nickname', sa.String(), nullable=False),
                    sa.Column('avatar_id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('nickname', name=op.f('player_pkey'))
                    )
    op.create_table('lobby',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('player1_nick', sa.String(), nullable=False),
                    sa.Column('player2_nick', sa.String(), nullable=True),
                    sa.Column('join_code', sa.UUID(), nullable=True),
                    sa.ForeignKeyConstraint(['player1_nick'], ['player.nickname'],
                                            name=op.f('lobby_player1_nick_fkey')),
                    sa.ForeignKeyConstraint(['player2_nick'], ['player.nickname'],
                                            name=op.f('lobby_player2_nick_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f('lobby_pkey'))
                    )
    op.create_table('game_settings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('holes_count', sa.Integer(), nullable=False),
                    sa.Column('stones_per_hole_count', sa.Integer(), nullable=False),
                    sa.Column('game_mode',
                              postgresql.ENUM('SINGLE_PLAYER', 'MULTIPLAYER', name='gamemode', create_type=False),
                              nullable=False),
                    sa.Column('lobby_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['lobby_id'], ['lobby.id'], name=op.f('game_settings_lobby_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f('game_settings_pkey'))
                    )
    op.create_table('game_state',
                    sa.Column('settings_id', sa.Integer(), nullable=False),
                    sa.Column('holes_player1', sa.ARRAY(sa.Integer()), nullable=False),
                    sa.Column('holes_player2', sa.ARRAY(sa.Integer()), nullable=False),
                    sa.Column('current_player', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['current_player'], ['player.nickname'],
                                            name=op.f('game_state_current_player_fkey')),
                    sa.ForeignKeyConstraint(['settings_id'], ['game_settings.id'],
                                            name=op.f('game_state_settings_id_fkey')),
                    sa.PrimaryKeyConstraint('settings_id', name=op.f('game_state_pkey'))
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_state')
    op.drop_table('game_settings')
    op.drop_table('lobby')
    op.drop_table('player')
    sa.Enum('SINGLE_PLAYER', 'MULTIPLAYER', name='gamemode').drop(op.get_bind())
    # ### end Alembic commands ###
