"""Add difficulty and make current player turn nullable

Revision ID: d30ea5153c08
Revises: 0563d1e023f8
Create Date: 2025-04-21 10:24:09.700655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd30ea5153c08'
down_revision: Union[str, None] = '0563d1e023f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_settings', sa.Column('difficulty_level', sa.Integer, nullable=True))
    op.execute("""
        UPDATE game_settings SET difficulty_level = 3;
    """)
    op.alter_column("game_settings", "difficulty_level", nullable=False)
    op.alter_column('game_state', 'current_player',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_state', 'current_player',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('game_settings', 'difficulty_level')
    # ### end Alembic commands ###
